package com.iconectiv.irsf.portal.model.customer;
// Generated Jan 12, 2017 6:31:43 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BlackList generated by hbm2java
 */
@Entity
@Table(name="black_list")
public class BlackList  implements java.io.Serializable {
     private Integer id;
     private String customerId;
     private String phone;
     private Date lastUpdated;

    public BlackList() {
    }

	
    public BlackList(String customerId, String phone) {
        this.customerId = customerId;
        this.phone = phone;
    }
    public BlackList(String customerId, String phone, Date lastUpdated) {
       this.customerId = customerId;
       this.phone = phone;
       this.lastUpdated = lastUpdated;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="customer_id", nullable=false, length=45)
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
    
    @Column(name="phone", nullable=false, length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated", length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


