package com.iconectiv.irsf.portal.model.customer;
// Generated Mar 6, 2017 5:15:33 PM by Hibernate Tools 3.2.2.GA

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ListUploadRequest generated by hbm2java
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)

@Entity
@Table(name = "list_upload_request")
public class ListUploadRequest implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer listRefId;
	private ListDefintion listDefintion;
	private String fileName;
	private String delimiter;
	private String status;
	private String errorData;
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
	private Date lastUpdated;
	private String lastUpdatedBy;

	private String customerName;
	
	private List<String> data;

	private List<ListDetails> listDetailsList = new ArrayList<>();

	@Transient
	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public ListUploadRequest() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "list_ref_id", nullable = false)
	public Integer getListRefId() {
		return listRefId;
	}

	public void setListRefId(Integer listRefId) {
		this.listRefId = listRefId;
	}

	@Transient
	public ListDefintion getListDefintion() {
		return this.listDefintion;
	}

	public void setListDefintion(ListDefintion listDefintion) {
		this.listDefintion = listDefintion;
	}

	@Column(name = "file_name", nullable = false, length = 45)
	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "delimiter", nullable = false, length = 1)
	public String getDelimiter() {
		return this.delimiter;
	}

	public void setDelimiter(String delimiter) {
		this.delimiter = delimiter;
	}

	@Column(name = "status", nullable = false, length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "error_data", length = 16777215)
	public String getErrorData() {
		return this.errorData;
	}

	public void setErrorData(String errorData) {
		this.errorData = errorData;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "last_updated_by", nullable = false, length = 45)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Transient
	public List<String> getData() {
		return data;
	}

	public void setData(List<String> data) {
		this.data = data;
	}

	@Transient
	public List<ListDetails> getListDetailsList() {
		return this.listDetailsList;
	}

	public void setListDetailsList(List<ListDetails> listDetailsList) {
		this.listDetailsList = listDetailsList;
	}

}
