package com.iconectiv.irsf.portal.model.customer;
// Generated Mar 6, 2017 5:15:33 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ListDetails generated by hbm2java
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Entity
@Table(name = "list_details")
public class ListDetails implements java.io.Serializable {
    private Integer id;
    private Integer listRefId;
    private Integer upLoadRefId;
    private String dialPattern;
    private String description;
    private String notes;
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    private Date customerDate;
    private boolean active;
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    private Date lastUpdated;
    private String lastUpdatedBy;

    public ListDetails() {
    }

    @Override
    public boolean equals(Object v) {
        if (v instanceof ListDetails) {
            ListDetails obj = (ListDetails)v;
            if (this.id == null && obj.getId() == null) {
                return this.dialPattern.equals(obj.getDialPattern());
            }
            if ( (this.id == null && obj.getId() != null )|| ( this.id != null && obj.getId() == null )) {
                return false;
            }

            return this.id.equals(obj.getId()) && this.dialPattern.equals(obj.getDialPattern());
        }

        return false;
    }


    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "list_ref_id", nullable = false)
    public Integer getListRefId() {
        return listRefId;
    }

    public void setListRefId(Integer listRefId) {
        this.listRefId = listRefId;
    }

    @Column(name = "upload_req_ref_id")
    public Integer getUpLoadRefId() {
        return upLoadRefId;
    }

    public void setUpLoadRefId(Integer upLoadRefId) {
        this.upLoadRefId = upLoadRefId;
    }

    @Column(name = "dial_pattern", nullable = false, length = 45)
    public String getDialPattern() {
        return this.dialPattern;
    }

    public void setDialPattern(String dialPattern) {
        this.dialPattern = dialPattern;
    }

    @Column(name = "description", length = 100)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "notes", length = 100)
    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "customer_date", length = 10)
    public Date getCustomerDate() {
        return this.customerDate;
    }

    public void setCustomerDate(Date customerDate) {
        this.customerDate = customerDate;
    }

    @Column(name = "active", nullable = false)
    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_updated", nullable = false, length = 19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @Column(name = "last_updated_by", nullable = false, length = 45)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }


}


