package com.iconectiv.irsf.portal.model.common;
// Generated Mar 9, 2017 1:15:40 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * AuditTrail generated by hbm2java
 */
@Entity
@Table(name = "audit_trail")
public class AuditTrail implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String userName;
	private String customerName;
	private String action;
	private String details;
	private Date lastUpdated;
	private String lastUpdatedBy;

	public AuditTrail() {
	}

	public AuditTrail(String userName, String action, Date lastUpdated, String lastUpdatedBy) {
		this.userName = userName;
		this.action = action;
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public AuditTrail(String userName, String customerName, String action, String details, Date lastUpdated,
	        String lastUpdatedBy) {
		this.userName = userName;
		this.customerName = customerName;
		this.action = action;
		setDetails(details);
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_name", nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "customer_name", length = 45)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "action", nullable = false, length = 45)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "details", length = 1000)
	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		if (details != null && details.length() > 1000) {
			details = details.substring(0,999);
		}
		this.details = details;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "last_updated_by", nullable = false, length = 45)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
