package com.iconectiv.irsf.portal.model.common;
// Generated Mar 9, 2017 1:15:40 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CcNdcIndex generated by hbm2java
 */
@Entity
@Table(name="cc_ndc_index"
    ,catalog="irsfmast"
)
public class CcNdcIndex  implements java.io.Serializable {


     private String ccNdc;

    public CcNdcIndex() {
    }

    public CcNdcIndex(String ccNdc) {
       this.ccNdc = ccNdc;
    }
   
     @Id 
    
    @Column(name="cc_ndc", unique=true, nullable=false, length=18)
    public String getCcNdc() {
        return this.ccNdc;
    }
    
    public void setCcNdc(String ccNdc) {
        this.ccNdc = ccNdc;
    }




}


