package com.iconectiv.irsf.portal.model.common;
// Generated Apr 14, 2017 1:41:25 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country", catalog = "irsfmast", uniqueConstraints = @UniqueConstraint(columnNames = { "code", "iso2" }))
public class Country implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String country;
	private String code;
	private String iso2;
	private String fips;
	private String iso3;
	private String isono;
	private String clmin;
	private String clmax;
	private String dststart;
	private String dstend;

	public Country() {
	}

	public Country(Integer id, String code, String iso2) {
		this.id = id;
		this.code = code;
		this.iso2 = iso2;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "country", length = 40)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "code", nullable = false, length = 3)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "iso2", nullable = false, length = 2)
	public String getIso2() {
		return this.iso2;
	}

	public void setIso2(String iso2) {
		this.iso2 = iso2;
	}

	@Column(name = "fips", length = 2)
	public String getFips() {
		return this.fips;
	}

	public void setFips(String fips) {
		this.fips = fips;
	}

	@Column(name = "iso3", length = 3)
	public String getIso3() {
		return this.iso3;
	}

	public void setIso3(String iso3) {
		this.iso3 = iso3;
	}

	@Column(name = "isono", length = 3)
	public String getIsono() {
		return this.isono;
	}

	public void setIsono(String isono) {
		this.isono = isono;
	}

	@Column(name = "clmin", length = 2)
	public String getClmin() {
		return this.clmin;
	}

	public void setClmin(String clmin) {
		this.clmin = clmin;
	}

	@Column(name = "clmax", length = 2)
	public String getClmax() {
		return this.clmax;
	}

	public void setClmax(String clmax) {
		this.clmax = clmax;
	}

	@Column(name = "dststart", length = 12)
	public String getDststart() {
		return this.dststart;
	}

	public void setDststart(String dststart) {
		this.dststart = dststart;
	}

	@Column(name = "dstend", length = 12)
	public String getDstend() {
		return this.dstend;
	}

	public void setDstend(String dstend) {
		this.dstend = dstend;
	}
	
	boolean isEqual(Country country) {
		return country.getCode().equals(this.code) && country.getIso2().equals(this.iso2);
	}

}
