package com.iconectiv.irsf.portal.model.common;
// Generated Mar 9, 2017 1:15:40 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="country"
    ,catalog="irsfmast"
)
public class Country  implements java.io.Serializable {


     private CountryId id;
     private String country;
     private String fips;
     private String iso3;
     private String isono;
     private String clmin;
     private String clmax;
     private String dststart;
     private String dstend;
     private Date loadDate;
     private String jobId;

    public Country() {
    }

	
    public Country(CountryId id, Date loadDate) {
        this.id = id;
        this.loadDate = loadDate;
    }
    public Country(CountryId id, String country, String fips, String iso3, String isono, String clmin, String clmax, String dststart, String dstend, Date loadDate, String jobId) {
       this.id = id;
       this.country = country;
       this.fips = fips;
       this.iso3 = iso3;
       this.isono = isono;
       this.clmin = clmin;
       this.clmax = clmax;
       this.dststart = dststart;
       this.dstend = dstend;
       this.loadDate = loadDate;
       this.jobId = jobId;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="code", column=@Column(name="code", nullable=false, length=3) ), 
        @AttributeOverride(name="iso2", column=@Column(name="iso2", nullable=false, length=2) ) } )
    public CountryId getId() {
        return this.id;
    }
    
    public void setId(CountryId id) {
        this.id = id;
    }
    
    @Column(name="country", length=40)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="fips", length=2)
    public String getFips() {
        return this.fips;
    }
    
    public void setFips(String fips) {
        this.fips = fips;
    }
    
    @Column(name="iso3", length=3)
    public String getIso3() {
        return this.iso3;
    }
    
    public void setIso3(String iso3) {
        this.iso3 = iso3;
    }
    
    @Column(name="isono", length=3)
    public String getIsono() {
        return this.isono;
    }
    
    public void setIsono(String isono) {
        this.isono = isono;
    }
    
    @Column(name="clmin", length=2)
    public String getClmin() {
        return this.clmin;
    }
    
    public void setClmin(String clmin) {
        this.clmin = clmin;
    }
    
    @Column(name="clmax", length=2)
    public String getClmax() {
        return this.clmax;
    }
    
    public void setClmax(String clmax) {
        this.clmax = clmax;
    }
    
    @Column(name="dststart", length=12)
    public String getDststart() {
        return this.dststart;
    }
    
    public void setDststart(String dststart) {
        this.dststart = dststart;
    }
    
    @Column(name="dstend", length=12)
    public String getDstend() {
        return this.dstend;
    }
    
    public void setDstend(String dstend) {
        this.dstend = dstend;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="load_date", nullable=false, length=19)
    public Date getLoadDate() {
        return this.loadDate;
    }
    
    public void setLoadDate(Date loadDate) {
        this.loadDate = loadDate;
    }
    
    @Column(name="job_id", length=16777215)
    public String getJobId() {
        return this.jobId;
    }
    
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }




}


