package com.iconectiv.irsf.portal.model.common;
// Generated Mar 9, 2017 1:15:40 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CountryId generated by hbm2java
 */
@Embeddable
public class CountryId  implements java.io.Serializable {


     private String code;
     private String iso2;

    public CountryId() {
    }

    public CountryId(String code, String iso2) {
       this.code = code;
       this.iso2 = iso2;
    }
   

    @Column(name="code", nullable=false, length=3)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    @Column(name="iso2", nullable=false, length=2)
    public String getIso2() {
        return this.iso2;
    }
    
    public void setIso2(String iso2) {
        this.iso2 = iso2;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CountryId) ) return false;
		 CountryId castOther = ( CountryId ) other; 
         
		 return ( (this.getCode()==castOther.getCode()) || ( this.getCode()!=null && castOther.getCode()!=null && this.getCode().equals(castOther.getCode()) ) )
 && ( (this.getIso2()==castOther.getIso2()) || ( this.getIso2()!=null && castOther.getIso2()!=null && this.getIso2().equals(castOther.getIso2()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCode() == null ? 0 : this.getCode().hashCode() );
         result = 37 * result + ( getIso2() == null ? 0 : this.getIso2().hashCode() );
         return result;
   }   


}


