package com.iconectiv.irsf.portal.model.common;
// Generated Mar 9, 2017 1:15:40 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DomainElementsId generated by hbm2java
 */
@Embeddable
public class DomainElementsId  implements java.io.Serializable {


     private String domain;
     private String domainValue;

    public DomainElementsId() {
    }

    public DomainElementsId(String domain, String domainValue) {
       this.domain = domain;
       this.domainValue = domainValue;
    }
   

    @Column(name="domain", nullable=false, length=12)
    public String getDomain() {
        return this.domain;
    }
    
    public void setDomain(String domain) {
        this.domain = domain;
    }

    @Column(name="domain_value", nullable=false, length=50)
    public String getDomainValue() {
        return this.domainValue;
    }
    
    public void setDomainValue(String domainValue) {
        this.domainValue = domainValue;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DomainElementsId) ) return false;
		 DomainElementsId castOther = ( DomainElementsId ) other; 
         
		 return ( (this.getDomain()==castOther.getDomain()) || ( this.getDomain()!=null && castOther.getDomain()!=null && this.getDomain().equals(castOther.getDomain()) ) )
 && ( (this.getDomainValue()==castOther.getDomainValue()) || ( this.getDomainValue()!=null && castOther.getDomainValue()!=null && this.getDomainValue().equals(castOther.getDomainValue()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDomain() == null ? 0 : this.getDomain().hashCode() );
         result = 37 * result + ( getDomainValue() == null ? 0 : this.getDomainValue().hashCode() );
         return result;
   }   


}


