package com.iconectiv.irsf.portal.model.common;
// Generated Mar 9, 2017 1:15:40 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

/**
 * DomainElements generated by hbm2java
 */
@Entity
@Table(name="domain_elements"
    ,catalog="irsfmast"
)
public class DomainElements  implements java.io.Serializable {


     private DomainElementsId id;

    public DomainElements() {
    }

    public DomainElements(DomainElementsId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="domain", column=@Column(name="domain", nullable=false, length=12) ), 
        @AttributeOverride(name="domainValue", column=@Column(name="domain_value", nullable=false, length=50) ) } )
    public DomainElementsId getId() {
        return this.id;
    }
    
    public void setId(DomainElementsId id) {
        this.id = id;
    }




}


