package com.iconectiv.irsf.portal.model.common;
// Generated Mar 9, 2017 1:15:40 PM by Hibernate Tools 3.2.2.GA

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * EventNotification generated by hbm2java
 */
@Entity
@Table(name = "event_notification")
public class EventNotification implements java.io.Serializable {
	private static final long serialVersionUID = -6197405739825807393L;
	private Integer id;
	private String customerName;
	private String eventType;
	private Integer severity = 1;
	private Integer referenceId;
	private String message;
	private String status = "new";
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:SS z")
	private Date createTimestamp;
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:SS z")
	private Date acknowledgeTimestamp;
	private String lastUpdatedBy;

	public EventNotification() {
	}

	public EventNotification(String eventType, String message, String status, Date createTimestamp) {
		this.eventType = eventType;
		this.message = message;
		this.status = status;
		this.createTimestamp = createTimestamp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "customer_name", length = 45)
	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}



	@Column(name = "event_type", nullable = false, length = 45)
	public String getEventType() {
		return this.eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

    @Column(name = "severity")
    public Integer getSeverity() {
        return severity;
    }

    public void setSeverity(Integer severity) {
        this.severity = severity;
    }

    @Column(name = "reference_id")
	public Integer getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(Integer referenceId) {
		this.referenceId = referenceId;
	}

	@Column(name = "message", nullable = false, length = 250)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		if (message != null && message.length() > 250) {
		    message = message.substring(0,249);
        }
	    this.message = message;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_timestamp", nullable = false, length = 19)
	public Date getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(Date createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "acknowledge_timestamp", length = 19)
	public Date getAcknowledgeTimestamp() {
		return this.acknowledgeTimestamp;
	}

	public void setAcknowledgeTimestamp(Date acknowledgeTimestamp) {
		this.acknowledgeTimestamp = acknowledgeTimestamp;
	}

	@Column(name = "last_updated_by", length = 45)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
