package com.iconectiv.irsf.portal.model.common;
// Generated Jan 12, 2017 11:20:13 AM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.springframework.data.annotation.TypeAlias;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ListUploadRequest generated by hbm2java
 */
@Entity
@Table(name="list_upload_request"
        ,catalog="irsf"
)
@TypeAlias("ListUploadRequest")
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class ListUploadRequest  implements java.io.Serializable {


    private Integer id;
    private String account;
    private String listName;
    private String type;
    private String path;
    private String status;
    
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd hh:mm:ss")
    private Date lastUpdated;

    public ListUploadRequest() {
    }

    public ListUploadRequest(String account, String listName, String path, String status, Date lastUpdated) {
        this.account = account;
        this.listName = listName;
        this.path = path;
        this.status = status;
        this.lastUpdated = lastUpdated;
    }

    @Id @GeneratedValue(strategy=IDENTITY)

    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="account", nullable=false, length=45)
    public String getAccount() {
        return this.account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    @Column(name="list_name", nullable=false, length=45)
    public String getListName() {
        return this.listName;
    }

    public void setListName(String listName) {
        this.listName = listName;
    }

    @Column(name="type", nullable=false, length=15)
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name="path", nullable=false, length=45)
    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    @Column(name="status", nullable=false, length=8)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated", nullable=false, length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


