package com.iconectiv.irsf.portal.model.common;
// Generated Mar 9, 2017 1:15:40 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Ndc generated by hbm2java
 */
@Entity
@Table(name = "ndc", catalog = "irsfmast")
public class Ndc implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String iso2;
	private String tos;
	private String tosdesc;
	private String ndc;
	private String locality;
	private String provider;
	private String utc;
	private String supplement;
	private String admindiv;
	private String billingid;
	private Date effectiveDate;
	private String pos;
	private Integer lemin;
	private Integer lemax;
	private String ocn;
	private String filler;
	private Date loadDate;
	private String jobId;

	public Ndc() {
	}

	public Ndc(Date loadDate) {
		this.loadDate = loadDate;
	}

	public Ndc(String iso2, String tos, String tosdesc, String ndc, String locality, String provider, String utc,
	        String supplement, String admindiv, String billingid, Date effectiveDate, String pos, Integer lemin,
	        Integer lemax, String ocn, String filler, Date loadDate, String jobId) {
		this.iso2 = iso2;
		this.tos = tos;
		this.tosdesc = tosdesc;
		this.ndc = ndc;
		this.locality = locality;
		this.provider = provider;
		this.utc = utc;
		this.supplement = supplement;
		this.admindiv = admindiv;
		this.billingid = billingid;
		this.effectiveDate = effectiveDate;
		this.pos = pos;
		this.lemin = lemin;
		this.lemax = lemax;
		this.ocn = ocn;
		this.filler = filler;
		this.loadDate = loadDate;
		this.jobId = jobId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "iso2", length = 2)
	public String getIso2() {
		return this.iso2;
	}

	public void setIso2(String iso2) {
		this.iso2 = iso2;
	}

	@Column(name = "tos", length = 1)
	public String getTos() {
		return this.tos;
	}

	public void setTos(String tos) {
		this.tos = tos;
	}

	@Column(name = "tosdesc", length = 20)
	public String getTosdesc() {
		return this.tosdesc;
	}

	public void setTosdesc(String tosdesc) {
		this.tosdesc = tosdesc;
	}

	@Column(name = "ndc", length = 10)
	public String getNdc() {
		return this.ndc;
	}

	public void setNdc(String ndc) {
		this.ndc = ndc;
	}

	@Column(name = "locality", length = 50)
	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	@Column(name = "provider", length = 50)
	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	@Column(name = "utc", length = 6)
	public String getUtc() {
		return this.utc;
	}

	public void setUtc(String utc) {
		this.utc = utc;
	}

	@Column(name = "supplement", length = 40)
	public String getSupplement() {
		return this.supplement;
	}

	public void setSupplement(String supplement) {
		this.supplement = supplement;
	}

	@Column(name = "admindiv", length = 20)
	public String getAdmindiv() {
		return this.admindiv;
	}

	public void setAdmindiv(String admindiv) {
		this.admindiv = admindiv;
	}

	@Column(name = "billingid", length = 10)
	public String getBillingid() {
		return this.billingid;
	}

	public void setBillingid(String billingid) {
		this.billingid = billingid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "effective_date", length = 10)
	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	@Column(name = "pos", length = 1)
	public String getPos() {
		return this.pos;
	}

	public void setPos(String pos) {
		this.pos = pos;
	}

	@Column(name = "lemin")
	public Integer getLemin() {
		return this.lemin;
	}

	public void setLemin(Integer lemin) {
		this.lemin = lemin;
	}

	@Column(name = "lemax")
	public Integer getLemax() {
		return this.lemax;
	}

	public void setLemax(Integer lemax) {
		this.lemax = lemax;
	}

	@Column(name = "ocn", length = 4)
	public String getOcn() {
		return this.ocn;
	}

	public void setOcn(String ocn) {
		this.ocn = ocn;
	}

	@Column(name = "filler", length = 12)
	public String getFiller() {
		return this.filler;
	}

	public void setFiller(String filler) {
		this.filler = filler;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "load_date", nullable = false, length = 19)
	public Date getLoadDate() {
		return this.loadDate;
	}

	public void setLoadDate(Date loadDate) {
		this.loadDate = loadDate;
	}

	@Column(name = "job_id", length = 16777215)
	public String getJobId() {
		return this.jobId;
	}

	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

}
