package com.iconectiv.irsf.portal.model.common;
// Generated Mar 9, 2017 1:15:40 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * PremRngFileLoadTracker generated by hbm2java
 */
@Entity
@Table(name="prem_rng_file_load_tracker"
    ,catalog="irsfmast"
)
public class PremRngFileLoadTracker  implements java.io.Serializable {


     private Integer id;
     private Character status;
     private Date loadDate;
     private String createdBy;
     private String uplFileName;
     private String lpnFileName;
     private String notes;
     private Integer springBatchJobId;

    public PremRngFileLoadTracker() {
    }

	
    public PremRngFileLoadTracker(Date loadDate) {
        this.loadDate = loadDate;
    }
    public PremRngFileLoadTracker(Character status, Date loadDate, String createdBy, String uplFileName, String lpnFileName, String notes, Integer springBatchJobId) {
       this.status = status;
       this.loadDate = loadDate;
       this.createdBy = createdBy;
       this.uplFileName = uplFileName;
       this.lpnFileName = lpnFileName;
       this.notes = notes;
       this.springBatchJobId = springBatchJobId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="load_date", nullable=false, length=19)
    public Date getLoadDate() {
        return this.loadDate;
    }
    
    public void setLoadDate(Date loadDate) {
        this.loadDate = loadDate;
    }
    
    @Column(name="created_by", length=25)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    
    @Column(name="upl_file_name", length=512)
    public String getUplFileName() {
        return this.uplFileName;
    }
    
    public void setUplFileName(String uplFileName) {
        this.uplFileName = uplFileName;
    }
    
    @Column(name="lpn_file_name", length=512)
    public String getLpnFileName() {
        return this.lpnFileName;
    }
    
    public void setLpnFileName(String lpnFileName) {
        this.lpnFileName = lpnFileName;
    }
    
    @Column(name="notes", length=512)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    @Column(name="spring_batch_job_id")
    public Integer getSpringBatchJobId() {
        return this.springBatchJobId;
    }
    
    public void setSpringBatchJobId(Integer springBatchJobId) {
        this.springBatchJobId = springBatchJobId;
    }




}


