package com.iconectiv.irsf.portal.model.common;
// Generated Mar 9, 2017 1:15:40 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * UnallocAlloc generated by hbm2java
 */
@Entity
@Table(name="unalloc_alloc"
    ,catalog="irsfmast"
)
public class UnallocAlloc  implements java.io.Serializable {


     private Integer id;
     private String iso2;
     private String ndc;
     private String indicator;
     private String filler;
     private Date loadDate;
     private String jobId;

    public UnallocAlloc() {
    }

	
    public UnallocAlloc(Date loadDate) {
        this.loadDate = loadDate;
    }
    public UnallocAlloc(String iso2, String ndc, String indicator, String filler, Date loadDate, String jobId) {
       this.iso2 = iso2;
       this.ndc = ndc;
       this.indicator = indicator;
       this.filler = filler;
       this.loadDate = loadDate;
       this.jobId = jobId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="iso2", length=2)
    public String getIso2() {
        return this.iso2;
    }
    
    public void setIso2(String iso2) {
        this.iso2 = iso2;
    }
    
    @Column(name="ndc", length=10)
    public String getNdc() {
        return this.ndc;
    }
    
    public void setNdc(String ndc) {
        this.ndc = ndc;
    }
    
    @Column(name="indicator", length=1)
    public String getIndicator() {
        return this.indicator;
    }
    
    public void setIndicator(String indicator) {
        this.indicator = indicator;
    }
    
    @Column(name="filler", length=12)
    public String getFiller() {
        return this.filler;
    }
    
    public void setFiller(String filler) {
        this.filler = filler;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="load_date", nullable=false, length=19)
    public Date getLoadDate() {
        return this.loadDate;
    }
    
    public void setLoadDate(Date loadDate) {
        this.loadDate = loadDate;
    }
    
    @Column(name="job_id", length=16777215)
    public String getJobId() {
        return this.jobId;
    }
    
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }




}


